build boxes with Vagrant file

diff --git a/test/pure-docker/Vagrantfile b/test/pure-docker/Vagrantfile
--- a/test/pure-docker/Vagrantfile
+++ b/test/pure-docker/Vagrantfile
@@ -36,6 +36,19 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
             override.vm.network "public_network", bridge: "ens4"
           end
 
+          config.vm.provision "shell", inline: <<-SHELL
+            #!/usr/bin/env bash
+            set -euxo pipefail
+            apt-get update
+            # Configure nameserver to avoid some DNS failures.
+            echo nameserver 8.8.8.8 > /etc/resolv.conf
+            # Install Docker
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+            sudo apt-get update -y
+            apt-cache policy docker-ce
+            apt-get install -y docker-ce docker-ce-cli containerd.io
+          SHELL
 
           servers["shell_commands"].each do |sh|
             srv.vm.provision "shell", inline: sh["shell"]
